# Generated by Django 4.1.1 on 2022-09-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bookappointment',
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
