# Generated by Django 4.1.1 on 2022-09-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_user_type_delete_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveIntegerField(choices=[(1, 'Patient'), (2, 'Doctor')], default=1),
        ),
    ]
