# Generated by Django 4.1.1 on 2022-09-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d')),
                ('category', models.PositiveIntegerField(choices=[('1', 'Mental Health'), ('2', 'Heart Disease'), ('3', 'Covid19'), ('4', 'Immunization')])),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=1000)),
            ],
        ),
    ]
