# Generated by Django 4.1.1 on 2022-09-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Mental Health'), (2, 'Heart Disease'), (3, 'Covid19'), (4, 'Immunization')], default=1),
        ),
    ]
