# Generated by Django 4.1.1 on 2022-09-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d')),
                ('category', models.PositiveIntegerField(choices=[(1, 'Mental Health'), (2, 'Heart Disease'), (3, 'Covid19'), (4, 'Immunization')], default=1)),
                ('content', models.TextField()),
                ('username', models.CharField(max_length=1000)),
            ],
        ),
    ]
